[package]
name = "pingora-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
pingora = "0.6"
async-trait = "0.1"
http = "1"
env_logger = "0.10"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
